default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres
  user: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432

development:
  <<: *default
  database: dummy_app_development

test:
  <<: *default
  database: dummy_app_test

production:
  <<: *default
  database: dummy_app_production
  username: dummy_app
  password: <%= ENV['DUMMY_APP_DATABASE_PASSWORD'] %>
