default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres
  user: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432

development:
  <<: *default
  database: damy_app_development

test:
  <<: *default
  database: damy_app_test

production:
  <<: *default
  database: damy_app_production
  username: damy_app
  password: <%= ENV['DAMY_APP_DATABASE_PASSWORD'] %>
